"""Merchants (first alias = merchant_id; statements often show legal names), people, employers, banks."""

# category -> list of alias lists
MERCHANTS = {
    "FOOD_DINING": [
        ["SWIGGY", "Swiggy Limited", "BUNDL TECHNOLOGIES", "SWIGGY FOOD"],
        ["ZOMATO", "Zomato Ltd", "ZOMATO ONLINE ORDER", "ETERNAL LIMITED", "ZOMATO MEDIA"],
        ["DOMINOS PIZZA", "JUBILANT FOODWORKS", "DOMINOS"],
        ["MCDONALDS", "HARDCASTLE RESTAURANTS", "CONNAUGHT PLAZA RESTAURANTS", "MC DONALDS"],
        ["KFC", "DEVYANI INTERNATIONAL", "SAPPHIRE FOODS INDIA"],
        ["STARBUCKS", "TATA STARBUCKS"],
        ["CAFE COFFEE DAY", "COFFEE DAY GLOBAL", "CCD"],
        ["HALDIRAMS", "HALDIRAM SNACKS", "HALDIRAM BHUJIAWALA"],
        ["BURGER KING", "RESTAURANT BRANDS ASIA"],
        ["CHAAYOS", "SUNSHINE TEAHOUSE"],
        ["BARBEQUE NATION", "BARBEQUE NATION HOSPITALITY"],
        ["EATSURE", "REBEL FOODS", "FAASOS", "BEHROUZ BIRYANI"],
        ["PIZZA HUT"],
        ["SUBWAY"],
        ["WOW MOMO", "WOW MOMO FOODS"],
        ["THIRD WAVE COFFEE"],
        ["BLUE TOKAI"],
        ["BASKIN ROBBINS", "GRAVISS FOODS"],
        ["THEOBROMA", "THEOBROMA FOODS"],
        ["MAGICPIN", "SAMAST TECHNOLOGIES"],
        ["CHAI POINT", "MOUNTAIN TRAIL FOODS"],
        ["BIKANERVALA"],
        ["SAGAR RATNA"],
        ["A2B", "ADYAR ANANDA BHAVAN"],
        ["PARADISE BIRYANI"],
        ["MEGHANA FOODS"],
        ["EMPIRE RESTAURANT"],
        ["TRUFFLES"],
        ["NATURALS ICE CREAM"],
        ["SOCIAL", "IMPRESARIO"],
        ["MAINLAND CHINA", "SPECIALITY RESTAURANTS"],
        ["BARISTA", "BARISTA COFFEE"],
        ["COSTA COFFEE"],
        ["TIM HORTONS"],
        ["DUNKIN", "DUNKIN DONUTS"],
        ["KRISPY KREME"],
        ["LA PINOZ PIZZA", "LAPINOZ"],
        ["OVENSTORY PIZZA"],
        ["MOJO PIZZA"],
        ["PIZZA EXPRESS"],
        ["TACO BELL"],
        ["NIRULAS"],
        ["SARAVANA BHAVAN", "HOTEL SARAVANA BHAVAN"],
        ["MTR RESTAURANT", "MAVALLI TIFFIN ROOMS"],
        ["VAANGO"],
        ["RAMESHWARAM CAFE"],
        ["CHAI SUTTA BAR"],
        ["GOLI VADA PAV"],
        ["JUMBOKING"],
        ["BIRYANI BLUES"],
        ["ARSALAN"],
        ["BAWARCHI"],
        ["SHAH GHOUSE"],
        ["KARIMS"],
        ["BURMA BURMA"],
        ["FARZI CAFE", "MASSIVE RESTAURANTS"],
        ["BIG CHILL"],
        ["CHILIS"],
        ["HARD ROCK CAFE"],
        ["PUNJAB GRILL"],
        ["PIND BALLUCHI"],
        ["EATFIT"],
        ["BOX8", "EATCLUB BRANDS"],
        ["FRESHMENU"],
        ["DINEOUT"],
        ["WOW CHINA"],
        ["POPEYES"],
        ["WENDYS"],
        ["HOCCO"],
        ["HUBER AND HOLLY"],
        ["CORNER HOUSE"],
        ["POLAR BEAR"],
        ["KEVENTERS"],
        ["BOBA BHAI"],
        ["TEA TRAILS"],
        ["BIRYANI BY KILO"],
        ["BEHROUZ"],
        ["OVEN STORY"],
    ],
    "GROCERIES": [
        ["BIGBASKET", "SUPERMARKET GROCERY SUPPLIES", "INNOVATIVE RETAIL CONCEPTS", "BB NOW"],
        ["BLINKIT", "BLINK COMMERCE", "GROFERS INDIA"],
        ["ZEPTO", "KIRANAKART TECHNOLOGIES", "GEDDIT CONVENIENCE"],
        ["SWIGGY INSTAMART", "INSTAMART"],
        ["DMART", "AVENUE SUPERMARTS", "D MART", "AVENUE E COMMERCE"],
        ["JIOMART", "RELIANCE RETAIL", "RELIANCE SMART", "RELIANCE FRESH"],
        ["MORE RETAIL", "MORE SUPERMARKET", "MORE MEGASTORE"],
        ["SPENCERS RETAIL", "SPENCERS"],
        ["STAR BAZAAR", "TRENT HYPERMARKET"],
        ["NATURES BASKET"],
        ["COUNTRY DELIGHT", "SUPERWELL COMFORTS"],
        ["MILKBASKET"],
        ["LICIOUS", "DELIGHTFUL GOURMET"],
        ["FRESHTOHOME", "FRESH TO HOME FOODS"],
        ["AMUL PARLOUR", "AMUL"],
        ["NANDINI MILK PARLOUR", "NANDINI"],
        ["MOTHER DAIRY", "SAFAL"],
        ["BIG BAZAAR"],
        ["RATNADEEP SUPERMARKET"],
        ["VISHAL MEGA MART"],
        ["FLIPKART MINUTES"],
        ["BB DAILY"],
        ["DUNZO DAILY", "DUNZO"],
        ["SPAR HYPERMARKET", "MAX HYPERMARKET"],
        ["EASYDAY"],
        ["HERITAGE FRESH"],
        ["METRO CASH AND CARRY"],
        ["WALMART BEST PRICE", "BEST PRICE"],
        ["LULU HYPERMARKET"],
        ["HOPCOMS"],
        ["KISANKONNECT"],
        ["OTIPY"],
        ["PLUCKK"],
        ["FRAAZO"],
        ["SUPR DAILY"],
        ["AKSHAYAKALPA"],
        ["HERITAGE MILK", "HERITAGE FOODS"],
        ["AAVIN"],
        ["VERKA"],
        ["GOKUL MILK"],
        ["SUGUNA CHICKEN"],
        ["ZORABIAN"],
        ["TENDERCUTS"],
        ["MEATIGO"],
        ["SMART BAZAAR"],
        ["RELIANCE SMART POINT"],
        ["DMART READY"],
        ["NILGIRIS"],
        ["FOODWORLD"],
        ["FARM FRESH"],
        ["ORGANIC WORLD"],
        ["24SEVEN"],
        ["KPN FRESH"],
        ["PAZHAMUDIR NILAYAM"],
        ["VIJETHA SUPERMARKET"],
        ["AMAZON FRESH", "AMAZONFRESH"],
        ["FLIPKART SUPERMART"],
        ["NAMDHARIS FRESH"],
        ["SAHAKARI BHANDAR"],
        ["APNA BAZAR"],
        ["KENDRIYA BHANDAR"],
    ],
    "SHOPPING": [
        ["AMAZON", "AMAZON PAY INDIA", "AMAZON SELLER SERVICES", "AMZN", "AMAZON INDIA", "AMAZONPAY"],
        ["FLIPKART", "FLIPKART INTERNET", "FLIPKART PAYMENTS", "FKRT"],
        ["MYNTRA", "MYNTRA DESIGNS"],
        ["AJIO", "RELIANCE AJIO"],
        ["MEESHO", "FASHNEAR TECHNOLOGIES"],
        ["NYKAA", "FSN E COMMERCE VENTURES", "NYKAA FASHION"],
        ["CROMA", "INFINITI RETAIL"],
        ["RELIANCE DIGITAL"],
        ["DECATHLON", "DECATHLON SPORTS INDIA"],
        ["IKEA", "IKEA INDIA"],
        ["LIFESTYLE", "LIFESTYLE INTERNATIONAL"],
        ["WESTSIDE", "TRENT LIMITED", "ZUDIO"],
        ["PANTALOONS", "ABFRL"],
        ["ZARA", "INDITEX TRENT"],
        ["H AND M", "H AND M HENNES", "HM INDIA"],
        ["MAX FASHION", "LANDMARK GROUP"],
        ["TATA CLIQ", "TATA UNISTORE"],
        ["LENSKART", "LENSKART SOLUTIONS"],
        ["PEPPERFRY"],
        ["SNAPDEAL"],
        ["FIRSTCRY", "BRAINBEES SOLUTIONS"],
        ["VIJAY SALES"],
        ["TANISHQ", "TITAN COMPANY"],
        ["BATA", "BATA INDIA"],
        ["PUMA", "PUMA SPORTS INDIA"],
        ["APPLE STORE", "APPLE INDIA"],
        ["BEWAKOOF", "BEWAKOOF BRANDS"],
        ["SHOPPERS STOP"],
        ["RELIANCE TRENDS", "TRENDS"],
        ["V MART", "V MART RETAIL"],
        ["CITYKART"],
        ["STYLE UNION"],
        ["FBB"],
        ["CENTRAL"],
        ["BRAND FACTORY"],
        ["UNIQLO"],
        ["MARKS AND SPENCER"],
        ["LEVIS", "LEVI STRAUSS"],
        ["ALLEN SOLLY"],
        ["VAN HEUSEN"],
        ["PETER ENGLAND"],
        ["RAYMOND"],
        ["MANYAVAR", "VEDANT FASHIONS"],
        ["FABINDIA"],
        ["BIBA"],
        ["W FOR WOMAN"],
        ["AURELIA"],
        ["GLOBAL DESI"],
        ["SOCH"],
        ["NALLI SILKS"],
        ["POTHYS"],
        ["CHENNAI SILKS"],
        ["KALYAN SILKS"],
        ["PURPLLE"],
        ["MAMAEARTH", "HONASA CONSUMER"],
        ["BOAT", "IMAGINE MARKETING"],
        ["NOISE"],
        ["SAMSUNG", "SAMSUNG INDIA"],
        ["MI STORE", "XIAOMI"],
        ["ONEPLUS"],
        ["REALME"],
        ["POORVIKA MOBILES"],
        ["SANGEETHA MOBILES"],
        ["BAJAJ ELECTRONICS"],
        ["PAI INTERNATIONAL"],
        ["LOT MOBILES"],
        ["HOMECENTRE", "HOME CENTRE"],
        ["HOMETOWN"],
        ["DUROFLEX"],
        ["WAKEFIT"],
        ["SLEEPYCAT"],
        ["NILKAMAL"],
        ["GODREJ INTERIO"],
        ["CAMPUS SHOES"],
        ["METRO SHOES"],
        ["MOCHI"],
        ["WOODLAND"],
        ["RED TAPE"],
        ["LIBERTY SHOES"],
        ["NIKE"],
        ["ADIDAS"],
        ["SKECHERS"],
        ["HAMLEYS"],
        ["CROSSWORD"],
        ["SAPNA BOOK HOUSE"],
        ["HIGGINBOTHAMS"],
        ["ARCHIES"],
        ["FERNS N PETALS", "FNP"],
        ["IGP"],
        ["CARATLANE"],
        ["MALABAR GOLD"],
        ["KALYAN JEWELLERS"],
        ["JOYALUKKAS"],
        ["PC JEWELLER"],
        ["BLUESTONE"],
        ["GIVA"],
        ["TITAN EYE PLUS"],
        ["FASTRACK"],
        ["TATA NEU"],
        ["SNITCH"],
        ["THE SOULED STORE"],
        ["LIMEROAD"],
        ["SHOPSY"],
        ["SPYKAR"],
        ["PEPE JEANS"],
        ["JACK AND JONES"],
        ["VERO MODA"],
        ["US POLO ASSN"],
        ["TOMMY HILFIGER"],
        ["LENOVO"],
        ["HP WORLD"],
        ["DELL"],
        ["ASUS"],
        ["SONY CENTER"],
        ["LG ELECTRONICS"],
        ["WHIRLPOOL"],
        ["VOLTAS"],
    ],
    "TRANSPORT": [
        ["UBER", "UBER INDIA SYSTEMS", "UBER RIDES"],
        ["OLA", "ANI TECHNOLOGIES", "OLACABS", "OLA CABS"],
        ["RAPIDO", "ROPPEN TRANSPORTATION"],
        ["NAMMA YATRI", "MOVING TECH"],
        ["BLUSMART", "BLUSMART MOBILITY"],
        ["DMRC", "DELHI METRO RAIL", "DELHI METRO"],
        ["MUMBAI METRO", "MUMBAI METRO ONE", "MMRDA METRO"],
        ["BMRCL", "NAMMA METRO", "BANGALORE METRO"],
        ["HYDERABAD METRO", "L AND T METRO RAIL"],
        ["CHENNAI METRO", "CMRL"],
        ["FASTAG", "NETC FASTAG", "FASTAG RECHARGE", "IHMCL", "PAYTM FASTAG"],
        ["BEST BUS", "BEST UNDERTAKING"],
        ["CHALO", "ZOPH TECHNOLOGIES"],
        ["YULU", "YULU BIKES"],
        ["PARK PLUS", "PARKPLUS"],
        ["MSRTC", "KSRTC", "TSRTC", "UPSRTC"],
        ["INDRIVE"],
        ["QUICK RIDE"],
        ["BOUNCE"],
        ["VOGO"],
        ["MERU CABS"],
        ["MEGA CABS"],
        ["SAVAARI"],
        ["GOZO CABS"],
        ["PUNE METRO", "MAHA METRO"],
        ["KOCHI METRO", "KMRL"],
        ["LUCKNOW METRO"],
        ["JAIPUR METRO"],
        ["AHMEDABAD METRO", "GMRC"],
        ["KOLKATA METRO"],
        ["NAMO BHARAT", "NCRTC", "RAPIDX"],
        ["UTS MOBILE TICKET", "CRIS UTS"],
        ["MTC BUS"],
        ["BMTC"],
        ["DTC BUS"],
        ["APSRTC"],
        ["GSRTC"],
        ["RSRTC"],
        ["HRTC"],
        ["ICICI FASTAG"],
        ["HDFC FASTAG"],
        ["AIRTEL FASTAG"],
        ["SBI FASTAG"],
        ["PARKWHEELS"],
        ["GET MY PARKING"],
        ["GOMECHANIC"],
        ["MYTVS"],
        ["BOSCH CAR SERVICE"],
        ["MARUTI SUZUKI SERVICE"],
        ["HERO SERVICE CENTRE"],
        ["HONDA SERVICE"],
        ["NAMMA METRO CARD"],
    ],
    "FUEL": [
        ["INDIAN OIL", "IOCL", "IOC PETROL PUMP", "INDIANOIL"],
        ["HPCL", "HP PETROL PUMP", "HINDUSTAN PETROLEUM", "HP PAY"],
        ["BPCL", "BHARAT PETROLEUM", "BPCL PETROL PUMP"],
        ["SHELL", "SHELL INDIA MARKETS", "SHELL PETROL"],
        ["NAYARA", "NAYARA ENERGY"],
        ["JIO BP", "RELIANCE BP MOBILITY"],
        ["GAS FILLING STATION", "FUEL STATION", "PETROL PUMP"],
        ["TATA POWER EZ CHARGE"],
        ["STATIQ"],
        ["CHARGEZONE"],
        ["JIO BP PULSE"],
        ["ATHER GRID"],
        ["CNG STATION"],
        ["IOCL XTRAPOWER"],
        ["BPCL SMARTDRIVE"],
        ["NAYARA PETROL PUMP"],
        ["ESSAR PETROL PUMP"],
    ],
    "TRAVEL": [
        ["IRCTC", "INDIAN RAILWAY CATERING", "IRCTC E TICKETING", "IRCTC WEB"],
        ["MAKEMYTRIP", "MAKEMYTRIP INDIA", "MMT"],
        ["GOIBIBO", "IBIBO GROUP"],
        ["CLEARTRIP"],
        ["YATRA", "YATRA ONLINE"],
        ["EASEMYTRIP", "EASY TRIP PLANNERS"],
        ["INDIGO", "INTERGLOBE AVIATION", "INDIGO AIRLINES"],
        ["AIR INDIA", "AIR INDIA LTD", "AIR INDIA EXPRESS"],
        ["AKASA AIR", "SNV AVIATION"],
        ["SPICEJET"],
        ["OYO", "ORAVEL STAYS", "OYO ROOMS"],
        ["AIRBNB"],
        ["BOOKING COM", "BOOKING.COM"],
        ["AGODA"],
        ["REDBUS", "REDBUS INDIA"],
        ["ABHIBUS"],
        ["TAJ HOTELS", "INDIAN HOTELS CO"],
        ["ZOOMCAR", "ZOOMCAR INDIA"],
        ["IXIGO", "LE TRAVENUES"],
        ["THOMAS COOK"],
        ["SOTC"],
        ["VEENA WORLD"],
        ["ALLIANCE AIR"],
        ["STAR AIR"],
        ["VISTARA"],
        ["GO FIRST"],
        ["EMIRATES"],
        ["QATAR AIRWAYS"],
        ["SINGAPORE AIRLINES"],
        ["LUFTHANSA"],
        ["TREEBO"],
        ["FABHOTELS"],
        ["ZOSTEL"],
        ["GOSTOPS"],
        ["ITC HOTELS"],
        ["MARRIOTT"],
        ["HYATT"],
        ["LEMON TREE HOTELS"],
        ["GINGER HOTELS"],
        ["CLUB MAHINDRA"],
        ["STERLING HOLIDAYS"],
        ["HOLIDAY INN"],
        ["RADISSON"],
        ["OBEROI HOTELS"],
        ["TRIVAGO"],
        ["EXPEDIA"],
        ["KSTDC"],
        ["MTDC"],
        ["IRCTC TOURISM"],
        ["INTRCITY SMARTBUS"],
        ["ZINGBUS"],
        ["FRESHBUS"],
        ["NUEGO"],
        ["VRL TRAVELS"],
        ["SRS TRAVELS"],
        ["ORANGE TRAVELS"],
        ["KALLADA TRAVELS"],
        ["REVV"],
        ["VFS GLOBAL"],
        ["PASSPORT SEVA"],
        ["HOLIDAY IQ"],
        ["PICKYOURTRAIL"],
        ["TRAVELTRIANGLE"],
        ["MUSAFIR"],
    ],
    "BILLS_UTILITIES": [
        ["AIRTEL", "BHARTI AIRTEL", "AIRTEL PREPAID", "AIRTEL POSTPAID", "AIRTEL XSTREAM"],
        ["JIO", "RELIANCE JIO", "JIOINAPPDIRECT", "JIO PREPAID", "RELIANCE JIO INFOCOMM", "JIO FIBER"],
        ["VODAFONE IDEA", "VI PREPAID", "VI POSTPAID"],
        ["BSNL", "BSNL MOBILE", "BSNL FTTH"],
        ["BESCOM", "BANGALORE ELECTRICITY"],
        ["MSEDCL", "MAHAVITARAN", "MAHARASHTRA STATE ELECTRICITY"],
        ["TATA POWER", "TATA POWER DDL", "TPDDL"],
        ["BSES RAJDHANI", "BSES YAMUNA", "BSES"],
        ["TANGEDCO", "TNEB", "TNPDCL"],
        ["ADANI ELECTRICITY", "ADANI ELECTRICITY MUMBAI"],
        ["TSSPDCL", "TGSPDCL"],
        ["UPPCL", "PASCHIMANCHAL VIDYUT"],
        ["CESC", "CESC LIMITED"],
        ["KSEB", "KERALA STATE ELECTRICITY"],
        ["INDANE", "INDANE GAS", "INDIAN OIL INDANE"],
        ["HP GAS", "HPCL LPG"],
        ["BHARAT GAS", "BPCL LPG"],
        ["MAHANAGAR GAS", "MGL"],
        ["INDRAPRASTHA GAS", "IGL"],
        ["BWSSB", "DELHI JAL BOARD", "WATER SUPPLY BOARD"],
        ["ACT FIBERNET", "ATRIA CONVERGENCE"],
        ["HATHWAY", "HATHWAY BROADBAND"],
        ["EXCITEL", "EXCITEL BROADBAND"],
        ["TATA PLAY", "TATA SKY", "TATA PLAY FIBER"],
        ["DISH TV", "DISHTV"],
        ["SUN DIRECT"],
        ["BILLDESKRECHARGE", "BILLDESK"],
        ["EURONETGPAY", "EURONET", "EURO NET BILL", "GPAY BILL PAYMENT", "PHONEPE BILL PAYMENT"],
        ["GPAYRECHARGE", "GPAYBILLRECHARGE", "GOOGLE PAY RECHARGE"],
        ["PAYTM RECHARGE", "PAYTM BILL PAYMENT"],
        ["FREECHARGE"],
        ["MYGATE", "VIVISH TECHNOLOGIES"],
        ["NOBROKERHOOD"],
        ["APSPDCL"],
        ["APEPDCL"],
        ["JVVNL", "JAIPUR VIDYUT VITRAN"],
        ["AVVNL"],
        ["JDVVNL"],
        ["MPPKVVCL"],
        ["MPMKVVCL"],
        ["PSPCL"],
        ["DHBVN"],
        ["UHBVN"],
        ["WBSEDCL"],
        ["NBPDCL"],
        ["SBPDCL"],
        ["CSPDCL"],
        ["TORRENT POWER"],
        ["BEST ELECTRICITY"],
        ["TPCODL", "TP CENTRAL ODISHA"],
        ["GESCOM"],
        ["HESCOM"],
        ["MESCOM"],
        ["CESC MYSORE"],
        ["APDCL"],
        ["GOA ELECTRICITY"],
        ["NDMC ELECTRICITY"],
        ["GUJARAT GAS"],
        ["ADANI TOTAL GAS"],
        ["TORRENT GAS"],
        ["SABARMATI GAS"],
        ["BHAGYANAGAR GAS"],
        ["HMWSSB"],
        ["CMWSSB"],
        ["BBMP PROPERTY TAX"],
        ["MCGM PROPERTY TAX"],
        ["GHMC PROPERTY TAX"],
        ["YOU BROADBAND"],
        ["TIKONA"],
        ["SPECTRANET"],
        ["ALLIANCE BROADBAND"],
        ["GTPL"],
        ["ASIANET BROADBAND"],
        ["DEN NETWORKS"],
        ["SITI CABLE"],
        ["AIRTEL DIGITAL TV"],
        ["D2H", "VIDEOCON D2H"],
        ["MOBIKWIK RECHARGE"],
        ["AIRTEL BLACK"],
        ["JIO POSTPAID"],
        ["MTNL"],
        ["RAILWIRE"],
    ],
    "RENT": [
        ["NOBROKER RENT", "NOBROKER TECHNOLOGIES", "NOBROKER"],
        ["CRED RENTPAY", "CRED RENT"],
        ["HOUSING COM RENT", "HOUSING.COM"],
        ["MAGICBRICKS RENT"],
        ["NESTAWAY"],
        ["STANZA LIVING"],
        ["ZOLO STAYS"],
        ["COLIVE"],
        ["YOUR SPACE"],
        ["ISTHARA"],
        ["OYO LIFE"],
        ["SQUARE YARDS RENT"],
        ["PAYTM RENT"],
        ["PHONEPE RENT"],
        ["REDGIRAFFE"],
        ["HOUSING RENT PAY"],
    ],
    "ENTERTAINMENT": [
        ["NETFLIX", "NETFLIX ENTERTAINMENT", "NETFLIX.COM"],
        ["AMAZON PRIME", "PRIME VIDEO", "AMAZON PRIME MEMBERSHIP"],
        ["JIOHOTSTAR", "DISNEY HOTSTAR", "NOVI DIGITAL", "STAR INDIA", "JIOSTAR"],
        ["SPOTIFY", "SPOTIFY INDIA"],
        ["YOUTUBE PREMIUM", "GOOGLE YOUTUBE", "YOUTUBE"],
        ["SONYLIV", "CULVER MAX ENTERTAINMENT"],
        ["ZEE5", "ZEE ENTERTAINMENT"],
        ["APPLE MEDIA SERVICES", "APPLE.COM BILL", "APPLE SERVICES", "ITUNES"],
        ["BOOKMYSHOW", "BIGTREE ENTERTAINMENT", "BMS"],
        ["PVR INOX", "PVR CINEMAS", "INOX LEISURE"],
        ["DISTRICT", "DISTRICT MOVIES"],
        ["CINEPOLIS"],
        ["GOOGLE PLAY", "GOOGLEPLAY", "GOOGLE PLAY STORE"],
        ["STEAM", "VALVE STEAM"],
        ["DREAM11", "SPORTA TECHNOLOGIES"],
        ["MPL", "GALACTUS FUNWARE"],
        ["WONDERLA", "WONDERLA HOLIDAYS"],
        ["TIMEZONE", "TIMEZONE ENTERTAINMENT"],
        ["AUDIBLE"],
        ["JIOCINEMA"],
        ["ALTBALAJI"],
        ["MX PLAYER"],
        ["SUN NXT"],
        ["AHA"],
        ["HOICHOI"],
        ["EROS NOW"],
        ["LIONSGATE PLAY"],
        ["MUBI"],
        ["DISCOVERY PLUS"],
        ["VOOT"],
        ["HUNGAMA"],
        ["GAANA"],
        ["JIOSAAVN"],
        ["WYNK MUSIC"],
        ["APPLE MUSIC"],
        ["AMAZON MUSIC"],
        ["KUKU FM"],
        ["POCKET FM"],
        ["STORYTEL"],
        ["PLAYSTATION STORE", "SONY PLAYSTATION"],
        ["XBOX"],
        ["NINTENDO"],
        ["EPIC GAMES"],
        ["RIOT GAMES"],
        ["KRAFTON", "BGMI"],
        ["GARENA FREE FIRE"],
        ["WINZO"],
        ["RUMMYCIRCLE", "GAMES24X7"],
        ["MY11CIRCLE"],
        ["POKERBAAZI"],
        ["PAYTM INSIDER", "INSIDER"],
        ["TICKETNEW"],
        ["IMAGICAA"],
        ["ESSELWORLD"],
        ["SNOW WORLD"],
        ["KIDZANIA"],
        ["SMAAASH"],
        ["CARNIVAL CINEMAS"],
        ["MIRAJ CINEMAS"],
        ["SPI CINEMAS"],
        ["ASIAN CINEMAS"],
        ["MOVIETIME CINEMAS"],
    ],
    "HEALTH": [
        ["APOLLO PHARMACY", "APOLLO HEALTHCO", "APOLLO 247"],
        ["PHARMEASY", "AXELIA SOLUTIONS"],
        ["TATA 1MG", "1MG TECHNOLOGIES", "1MG"],
        ["NETMEDS", "NETMEDS MARKETPLACE"],
        ["MEDPLUS", "OPTIVAL HEALTH SOLUTIONS"],
        ["TRUEMEDS"],
        ["PRACTO", "PRACTO TECHNOLOGIES"],
        ["APOLLO HOSPITALS", "APOLLO HOSPITALS ENTERPRISE"],
        ["FORTIS HOSPITAL", "FORTIS HEALTHCARE"],
        ["MAX HEALTHCARE", "MAX HOSPITAL"],
        ["MANIPAL HOSPITALS"],
        ["NARAYANA HEALTH"],
        ["DR LAL PATHLABS", "LAL PATHLABS"],
        ["THYROCARE", "THYROCARE TECHNOLOGIES"],
        ["METROPOLIS HEALTHCARE"],
        ["WELLNESS FOREVER"],
        ["MEDLIFE"],
        ["FRANK ROSS"],
        ["GUARDIAN PHARMACY"],
        ["NOBLE PLUS"],
        ["HEALTHKART"],
        ["CARE HOSPITALS"],
        ["ASTER DM", "ASTER HOSPITAL"],
        ["KIMS HOSPITAL"],
        ["YASHODA HOSPITALS"],
        ["MEDANTA"],
        ["KOKILABEN HOSPITAL"],
        ["LILAVATI HOSPITAL"],
        ["HINDUJA HOSPITAL"],
        ["RAINBOW CHILDRENS HOSPITAL"],
        ["CLOUDNINE"],
        ["MOTHERHOOD HOSPITAL"],
        ["SANKARA NETHRALAYA"],
        ["DR AGARWALS EYE HOSPITAL"],
        ["CLOVE DENTAL"],
        ["SABKA DENTIST"],
        ["AGILUS DIAGNOSTICS", "SRL DIAGNOSTICS"],
        ["VIJAYA DIAGNOSTIC"],
        ["NEUBERG DIAGNOSTICS"],
        ["REDCLIFFE LABS"],
        ["HEALTHIANS"],
        ["ORANGE HEALTH"],
        ["MFINE"],
        ["AIIMS"],
        ["CMC VELLORE"],
        ["NARAYANA NETHRALAYA"],
        ["APOLLO CLINIC"],
        ["COLUMBIA ASIA"],
        ["SIR GANGA RAM HOSPITAL"],
        ["JASLOK HOSPITAL"],
        ["NANAVATI HOSPITAL"],
        ["TATA MEMORIAL"],
        ["ARTEMIS HOSPITAL"],
        ["BLK MAX"],
        ["MEDICOVER"],
    ],
    "EDUCATION": [
        ["BYJUS", "THINK AND LEARN"],
        ["UNACADEMY", "SORTING HAT TECHNOLOGIES"],
        ["PHYSICSWALLAH", "PHYSICS WALLAH"],
        ["UPGRAD", "UPGRAD EDUCATION"],
        ["COURSERA"],
        ["UDEMY"],
        ["VEDANTU", "VEDANTU INNOVATIONS"],
        ["SIMPLILEARN"],
        ["SCALER", "INTERVIEWBIT TECHNOLOGIES"],
        ["GREAT LEARNING"],
        ["ALLEN CAREER INSTITUTE", "ALLEN KOTA"],
        ["AAKASH INSTITUTE", "AAKASH EDUCATIONAL"],
        ["NTA EXAM FEE", "EXAM FEE"],
        ["CHEGG"],
        ["WHITEHAT JR"],
        ["CUEMATH"],
        ["TOPPR"],
        ["EMBIBE"],
        ["ADDA247"],
        ["TESTBOOK"],
        ["OLIVEBOARD"],
        ["MADE EASY"],
        ["ACE ACADEMY"],
        ["FIITJEE"],
        ["RESONANCE"],
        ["VIDYAMANDIR CLASSES"],
        ["SRI CHAITANYA"],
        ["NARAYANA SCHOOLS"],
        ["TIME INSTITUTE"],
        ["IMS LEARNING"],
        ["CAREER LAUNCHER"],
        ["DELHI PUBLIC SCHOOL", "DPS"],
        ["KENDRIYA VIDYALAYA"],
        ["RYAN INTERNATIONAL"],
        ["PODAR INTERNATIONAL"],
        ["ORCHIDS INTERNATIONAL"],
        ["AMITY UNIVERSITY"],
        ["MANIPAL ACADEMY"],
        ["VIT UNIVERSITY"],
        ["SRM UNIVERSITY"],
        ["LOVELY PROFESSIONAL UNIVERSITY", "LPU"],
        ["IGNOU"],
        ["NIOS"],
        ["CBSE"],
        ["UPSC EXAM FEE"],
        ["SSC EXAM FEE"],
        ["IBPS"],
        ["IDP IELTS", "IELTS"],
        ["BRITISH COUNCIL"],
        ["DUOLINGO"],
        ["SKILLSHARE"],
        ["EDX"],
        ["INTERNSHALA"],
        ["NEWTON SCHOOL"],
        ["MASAI SCHOOL"],
        ["ALMABETTER"],
        ["CODING NINJAS"],
        ["GEEKSFORGEEKS"],
        ["LINKEDIN LEARNING"],
        ["DATACAMP"],
        ["BRAINLY"],
    ],
    "PERSONAL_CARE": [
        ["URBAN COMPANY", "URBANCLAP TECHNOLOGIES", "URBANCLAP"],
        ["CULTFIT", "CURE FIT HEALTHCARE", "CULT FIT"],
        ["GOLDS GYM"],
        ["ANYTIME FITNESS"],
        ["LAKME SALON"],
        ["NATURALS SALON", "NATURALS"],
        ["ENRICH SALON"],
        ["JAWED HABIB"],
        ["YES MADAM"],
        ["TONI AND GUY"],
        ["LOOKS SALON"],
        ["GREEN TRENDS"],
        ["BODYCRAFT"],
        ["KAYA CLINIC"],
        ["VLCC"],
        ["O2 SPA"],
        ["TATTVA SPA"],
        ["FITPASS"],
        ["CRUNCH FITNESS"],
        ["SNAP FITNESS"],
        ["F45 TRAINING"],
        ["TALWALKARS"],
        ["MULTIFIT"],
        ["HEADMASTERS SALON"],
        ["YLG SALON"],
        ["BBLUNT"],
        ["GEETANJALI SALON"],
        ["HOUSEJOY"],
        ["FIT AND GLOW"],
        ["CULT PASS"],
        ["HABUILD"],
        ["HEALTHIFYME"],
    ],
    "EMI_LOAN": [
        ["BAJAJ FINANCE", "BAJAJ FINSERV", "BAJAJFIN", "BAJAJ FINANCE LTD"],
        ["HDFC BANK LOAN", "HDFC LTD LOAN", "HDFC LOAN EMI"],
        ["ICICI BANK LOAN", "ICICI LOAN"],
        ["SBI HOME LOAN", "SBI LOAN", "SBI CAR LOAN"],
        ["TATA CAPITAL", "TATA CAPITAL FINANCIAL"],
        ["HDB FINANCIAL SERVICES", "HDB FINANCIAL"],
        ["HOME CREDIT", "HOME CREDIT INDIA"],
        ["SMFG INDIA CREDIT", "FULLERTON INDIA"],
        ["KOTAK LOAN", "KOTAK MAHINDRA PRIME"],
        ["AXIS BANK LOAN"],
        ["LIC HOUSING FINANCE", "LIC HFL"],
        ["PNB HOUSING FINANCE"],
        ["MUTHOOT FINANCE", "MUTHOOT GOLD LOAN"],
        ["KREDITBEE", "KRAZYBEE SERVICES"],
        ["NAVI", "NAVI FINSERV"],
        ["MONEYVIEW", "WHIZDM FINANCE"],
        ["LAZYPAY", "PAYU FINANCE"],
        ["SIMPL", "ONE SIGMA TECHNOLOGIES"],
        ["MAHINDRA FINANCE", "MAHINDRA AND MAHINDRA FINANCIAL"],
        ["IDFC FIRST LOAN"],
        ["ADITYA BIRLA FINANCE"],
        ["L AND T FINANCE"],
        ["CHOLAMANDALAM", "CHOLA FINANCE"],
        ["SHRIRAM FINANCE"],
        ["POONAWALLA FINCORP"],
        ["HERO FINCORP"],
        ["TVS CREDIT"],
        ["IIFL FINANCE"],
        ["MANAPPURAM FINANCE"],
        ["CAPRI GLOBAL"],
        ["AAVAS FINANCIERS"],
        ["BAJAJ HOUSING FINANCE"],
        ["ICICI HOME FINANCE"],
        ["SAMMAAN CAPITAL", "INDIABULLS HOUSING"],
        ["AXIS FINANCE"],
        ["YES BANK LOAN"],
        ["INDUSIND LOAN"],
        ["FEDERAL BANK LOAN"],
        ["PAYSENSE"],
        ["CASHE"],
        ["FIBE", "EARLYSALARY"],
        ["STASHFIN"],
        ["MPOKKET"],
        ["TRUEBALANCE"],
        ["ZESTMONEY"],
        ["PAYTM POSTPAID"],
        ["AMAZON PAY LATER"],
        ["FLIPKART PAY LATER"],
        ["ICICI PAYLATER"],
        ["DMI FINANCE"],
        ["PIRAMAL FINANCE"],
        ["GODREJ FINANCE"],
        ["UGRO CAPITAL"],
        ["INCRED FINANCE"],
        ["KISSHT", "ONEMI TECHNOLOGY"],
        ["MONEYTAP"],
        ["BAJAJ FINSERV EMI CARD"],
        ["TATA CAPITAL HOUSING"],
    ],
    "CREDIT_CARD_BILL": [
        ["CRED", "CRED CLUB", "DREAMPLUG TECHNOLOGIES", "CRED BILL PAY"],
        ["HDFC CREDIT CARD", "HDFC CC", "HDFCCC"],
        ["SBI CARD", "SBI CARDS AND PAYMENT", "SBICARD"],
        ["ICICI CREDIT CARD", "ICICI CC"],
        ["AXIS CREDIT CARD", "AXIS CC"],
        ["AMEX", "AMERICAN EXPRESS"],
        ["ONECARD", "FPL TECHNOLOGIES"],
        ["KOTAK CREDIT CARD", "KOTAK CC"],
        ["IDFC FIRST CREDIT CARD"],
        ["RBL CREDIT CARD", "RBL CC"],
        ["INDUSIND CREDIT CARD"],
        ["YES BANK CREDIT CARD"],
        ["AU CREDIT CARD"],
        ["BOBCARD", "BOB CREDIT CARD"],
        ["HSBC CREDIT CARD"],
        ["STANDARD CHARTERED CC", "SCB CREDIT CARD"],
        ["CITI CREDIT CARD"],
        ["FEDERAL CREDIT CARD"],
        ["SCAPIA"],
        ["SLICE", "QUADRILLION FINANCE"],
        ["UNI CARD"],
        ["KIWI CREDIT"],
        ["PAYTM CC BILL"],
        ["PHONEPE CC BILL"],
        ["MOBIKWIK CC BILL"],
        ["CANARA CREDIT CARD"],
        ["PNB CREDIT CARD"],
    ],
    "INSURANCE": [
        ["LIC", "LIFE INSURANCE CORPORATION", "LICI", "LIC OF INDIA"],
        ["HDFC LIFE", "HDFC LIFE INSURANCE"],
        ["ICICI PRU LIFE", "ICICI PRUDENTIAL LIFE"],
        ["SBI LIFE", "SBI LIFE INSURANCE"],
        ["AXIS MAX LIFE", "MAX LIFE INSURANCE"],
        ["STAR HEALTH", "STAR HEALTH AND ALLIED"],
        ["NIVA BUPA", "MAX BUPA"],
        ["CARE HEALTH", "CARE HEALTH INSURANCE"],
        ["ACKO", "ACKO GENERAL INSURANCE"],
        ["GO DIGIT", "DIGIT INSURANCE"],
        ["POLICYBAZAAR", "PB FINTECH", "POLICY BAZAAR"],
        ["BAJAJ ALLIANZ", "BAJAJ GENERAL INSURANCE"],
        ["TATA AIA", "TATA AIA LIFE"],
        ["PMJJBY", "PMJJBY PREMIUM"],
        ["PMSBY", "PMSBY PREMIUM"],
        ["NEW INDIA ASSURANCE"],
        ["KOTAK LIFE"],
        ["PNB METLIFE"],
        ["BAJAJ ALLIANZ LIFE"],
        ["ADITYA BIRLA SUN LIFE INSURANCE"],
        ["ADITYA BIRLA HEALTH"],
        ["CANARA HSBC LIFE"],
        ["BANDHAN LIFE"],
        ["EDELWEISS LIFE"],
        ["SHRIRAM LIFE"],
        ["IFFCO TOKIO"],
        ["TATA AIG"],
        ["HDFC ERGO"],
        ["ICICI LOMBARD"],
        ["RELIANCE GENERAL INSURANCE"],
        ["SBI GENERAL INSURANCE"],
        ["UNITED INDIA INSURANCE"],
        ["ORIENTAL INSURANCE"],
        ["NATIONAL INSURANCE"],
        ["CHOLA MS"],
        ["ROYAL SUNDARAM"],
        ["FUTURE GENERALI"],
        ["LIBERTY GENERAL"],
        ["MANIPALCIGNA"],
        ["COVERFOX"],
        ["TURTLEMINT"],
        ["INSURANCEDEKHO"],
        ["RENEWBUY"],
        ["DITTO INSURANCE"],
    ],
    "INVESTMENT": [
        ["ZERODHA", "ZERODHA BROKING", "ZERODHA COIN"],
        ["GROWW", "NEXTBILLION TECHNOLOGY", "GROWW INVEST TECH"],
        ["UPSTOX", "RKSV SECURITIES"],
        ["ANGEL ONE", "ANGEL BROKING"],
        ["ICICI SECURITIES", "ICICIDIRECT"],
        ["KUVERA"],
        ["BSE LIMITED", "BSE STAR MF", "BSE LTD"],
        ["INDIAN CLEARING CORP", "ICCL", "INDIAN CLEARING CORPORATION"],
        ["NSE CLEARING", "NSCCL", "NSE CLEARING LTD"],
        ["CAMS", "COMPUTER AGE MANAGEMENT"],
        ["KFINTECH", "KFIN TECHNOLOGIES"],
        ["SBI MUTUAL FUND", "SBI MF"],
        ["HDFC MUTUAL FUND", "HDFC MF"],
        ["PPFAS MUTUAL FUND", "PARAG PARIKH MF"],
        ["ICICI PRU MF", "ICICI PRUDENTIAL MF"],
        ["AXIS MUTUAL FUND", "AXIS MF"],
        ["NPS TRUST", "PROTEAN NPS", "NPS CONTRIBUTION"],
        ["JAR", "CHANGEJAR"],
        ["SAFEGOLD", "DIGITAL GOLD"],
        ["INDMONEY", "INDMONEY INVEST"],
        ["PAYTM MONEY"],
        ["DHAN", "RAISE SECURITIES"],
        ["MOTILAL OSWAL"],
        ["HDFC SECURITIES"],
        ["KOTAK SECURITIES"],
        ["SHAREKHAN"],
        ["5PAISA"],
        ["FYERS"],
        ["SAMCO"],
        ["SMALLCASE"],
        ["ET MONEY"],
        ["SCRIPBOX"],
        ["FISDOM"],
        ["NIPPON INDIA MF"],
        ["KOTAK MF"],
        ["MIRAE ASSET MF"],
        ["UTI MF"],
        ["QUANT MF"],
        ["DSP MF"],
        ["TATA MF"],
        ["ADITYA BIRLA SUN LIFE MF"],
        ["FRANKLIN TEMPLETON"],
        ["EDELWEISS MF"],
        ["MOTILAL OSWAL MF"],
        ["CANARA ROBECO"],
        ["INVESCO MF"],
        ["BANDHAN MF"],
        ["HSBC MF"],
        ["WINT WEALTH"],
        ["GRIP INVEST"],
        ["GOLDENPI"],
        ["STABLE MONEY"],
        ["AUGMONT"],
        ["MMTC PAMP"],
        ["SOVEREIGN GOLD BOND"],
        ["RBI RETAIL DIRECT"],
        ["INDIA POST RD", "POST OFFICE SAVINGS"],
        ["COINDCX"],
        ["COINSWITCH"],
        ["WAZIRX"],
        ["MUDREX"],
    ],
}

# Local / small businesses are generated as "<prefix> <suffix>".
LOCAL_PREFIXES = [
    "SHREE", "SRI", "NEW", "OM SAI", "BALAJI", "GANESH", "LAXMI", "MAHALAXMI", "JAI MATA DI",
    "KRISHNA", "ANNAPURNA", "RAJ", "SAI", "GURU", "NAVRANG", "ROYAL", "A1", "STAR", "CITY",
    "PATEL", "SHARMA", "GUPTA", "AGARWAL", "REDDY", "NAIR", "IYER", "SINGH", "KHAN", "MEHTA",
    "JAIN", "MURUGAN", "VINAYAKA", "VENKATESWARA", "AMBIKA", "DURGA", "SIDDHI VINAYAK", "HARI OM",
    "GOPAL", "MADINA", "NEW DELHI", "BOMBAY", "KAVERI", "GANGA", "SUNRISE", "GREEN",
]

LOCAL_SUFFIXES = {
    "FOOD_DINING": ["RESTAURANT", "FAST FOOD", "DHABA", "SWEETS", "BAKERY", "CAFE", "TIFFIN CENTRE",
                    "HOTEL", "BIRYANI HOUSE", "TEA STALL", "JUICE CENTRE", "FOOD COURT", "BHOJNALAYA",
                    "DOSA CORNER", "MOMOS", "SWEET HOUSE", "CHAAT BHANDAR", "UDUPI HOTEL", "MESS"],
    "GROCERIES": ["KIRANA STORE", "GENERAL STORE", "PROVISION STORE", "SUPERMARKET", "TRADERS",
                  "DAIRY", "MILK CENTRE", "VEGETABLES", "FRUITS", "MART", "FRESH MART",
                  "KIRANA AND GENERAL STORES", "DEPARTMENTAL STORE", "EGG CENTRE", "CHICKEN CENTRE"],
    "SHOPPING": ["GARMENTS", "TEXTILES", "FOOTWEAR", "ELECTRONICS", "MOBILE SHOP", "FASHION",
                 "COLLECTION", "JEWELLERS", "GIFT CENTRE", "STATIONERY", "HARDWARE", "FURNITURE",
                 "OPTICALS", "BOOK DEPOT", "SAREE CENTRE", "MOBILES AND ACCESSORIES"],
    "HEALTH": ["MEDICAL STORE", "MEDICALS", "PHARMACY", "CHEMIST", "CLINIC", "DIAGNOSTICS",
               "HOSPITAL", "DENTAL CLINIC", "PATH LAB", "MEDICOS", "NURSING HOME", "EYE CARE"],
    "FUEL": ["PETROLEUM", "FILLING STATION", "FUELS", "SERVICE STATION", "PETROL PUMP", "AUTO FUELS",
             "KISAN SEVA KENDRA"],
    "PERSONAL_CARE": ["SALON", "BEAUTY PARLOUR", "UNISEX SALON", "HAIR SALOON", "SPA", "FITNESS",
                      "GYM", "FITNESS CLUB", "MENS PARLOUR"],
    "EDUCATION": ["PUBLIC SCHOOL", "ACADEMY", "COACHING CENTRE", "TUTORIALS", "CLASSES", "VIDYALAYA",
                  "CONVENT SCHOOL", "INSTITUTE", "COLLEGE", "INTERNATIONAL SCHOOL", "DANCE ACADEMY"],
    "TRANSPORT": ["TRAVELS", "TAXI SERVICE", "PARKING", "TOURS AND TRAVELS", "CAR WASH",
                  "AUTO GARAGE", "TYRE SHOP", "MOTORS SERVICE"],
    "ENTERTAINMENT": ["CINEMAS", "MULTIPLEX", "GAMING ZONE", "SPORTS CLUB", "BOWLING", "TALKIES"],
    "BILLS_UTILITIES": ["CO OP HOUSING SOCIETY", "APARTMENT OWNERS ASSN", "RESIDENTS WELFARE ASSN",
                        "CABLE NETWORK", "WATER SUPPLY", "BROADBAND SERVICES"],
}

FIRST_NAMES = [
    "RAHUL", "PRIYA", "AMIT", "SNEHA", "VIKRAM", "ANJALI", "ROHIT", "POOJA", "ARJUN", "NEHA",
    "SURESH", "KAVYA", "RAJESH", "DIVYA", "KARTHIK", "LAKSHMI", "MOHAMMED", "FATIMA", "IMRAN",
    "AYESHA", "GURPREET", "HARPREET", "MANPREET", "SIMRAN", "ANIL", "SUNITA", "RAMESH", "GEETA",
    "VENKATESH", "SWATHI", "PRAVEEN", "MEENA", "ABHISHEK", "SHREYA", "SAURABH", "RITU", "DEEPAK",
    "NISHA", "ARUN", "ANITHA", "SANJAY", "REKHA", "VIJAY", "JYOTI", "ASHOK", "PAYEL", "SOUMYA",
    "BIPLAB", "ANANYA", "KAUSHIK", "JOSEPH", "MARY", "THOMAS", "SHALINI", "NIKHIL", "TANVI",
    "YASH", "ISHA", "HARSH", "KOMAL", "MANOJ", "USHA", "SRINIVAS", "PADMA", "GOPAL", "SEEMA",
    "ADITYA", "RIYA", "PRAKASH", "BHAVNA", "SACHIN", "MAMTA", "AKSHAY", "VARSHA", "RAJU", "RAMU",
]
LAST_NAMES = [
    "SHARMA", "VERMA", "GUPTA", "SINGH", "KUMAR", "PATEL", "SHAH", "MEHTA", "REDDY", "RAO",
    "NAIR", "MENON", "PILLAI", "IYER", "IYENGAR", "SUBRAMANIAN", "KRISHNAN", "MUKHERJEE",
    "BANERJEE", "CHATTERJEE", "SENGUPTA", "SAHA", "DAS", "GHOSH", "BOSE", "KHAN", "SHAIKH",
    "ANSARI", "QURESHI", "SIDDIQUI", "GILL", "SANDHU", "DHILLON", "KAUR", "JOSHI", "KULKARNI",
    "DESHPANDE", "PATIL", "JADHAV", "PAWAR", "YADAV", "MISHRA", "PANDEY", "TIWARI", "DUBEY",
    "CHOUDHARY", "JAIN", "AGARWAL", "BANSAL", "GOEL", "D SOUZA", "FERNANDES", "THOMAS", "JOSEPH",
    "NAIDU", "GOWDA", "HEGDE", "SHETTY", "BHAT", "MALIK", "THAKUR", "RATHORE", "CHAUHAN",
]

EMPLOYERS = [
    "TATA CONSULTANCY SERVICES", "INFOSYS LIMITED", "WIPRO LIMITED", "HCL TECHNOLOGIES",
    "ACCENTURE SOLUTIONS", "COGNIZANT TECHNOLOGY", "TECH MAHINDRA", "CAPGEMINI TECHNOLOGY",
    "IBM INDIA", "DELOITTE SHARED SERVICES", "LTIMINDTREE", "RELIANCE INDUSTRIES", "HDFC BANK",
    "ICICI BANK", "AMAZON DEVELOPMENT CENTRE", "FLIPKART INTERNET", "SWIGGY LIMITED",
    "MAHINDRA AND MAHINDRA", "LARSEN AND TOUBRO", "ASIAN PAINTS", "ITC LIMITED", "BYJUS",
    "GOOGLE INDIA", "MICROSOFT CORPORATION INDIA", "ORACLE INDIA", "ZOHO CORPORATION",
    "FRESHWORKS TECHNOLOGIES", "PAYTM", "OLA ELECTRIC", "MARUTI SUZUKI", "BAJAJ AUTO",
    "APOLLO HOSPITALS", "DMART", "GOVT OF MAHARASHTRA", "GOVT OF KARNATAKA", "INDIAN RAILWAYS",
    "STATE BANK OF INDIA",
]
EMPLOYER_SMALL_SUFFIX = ["ENTERPRISES", "PVT LTD", "PRIVATE LIMITED", "SOLUTIONS", "TECHNOLOGIES",
                         "INDUSTRIES", "TRADERS", "ASSOCIATES", "CONSULTANTS", "LLP", "EXPORTS"]

DIVIDEND_COMPANIES = ["INFOSYS", "TCS", "ITC", "HDFC BANK", "RELIANCE", "COAL INDIA", "ONGC",
                      "HINDUSTAN UNILEVER", "WIPRO", "SBI", "BAJAJ AUTO", "VEDANTA", "POWER GRID",
                      "NTPC", "HERO MOTOCORP", "TATA STEEL", "ASIAN PAINTS", "IRCTC", "NESTLE INDIA"]
AMCS = ["SBI MF", "HDFC MF", "ICICI PRU MF", "AXIS MF", "PPFAS MF", "NIPPON INDIA MF", "KOTAK MF",
        "MIRAE ASSET MF", "UTI MF", "QUANT MF", "MOTILAL OSWAL MF", "TATA MF", "DSP MF"]

# (display name, IFSC prefix)
BANKS = [
    ("STATE BANK OF INDIA", "SBIN"), ("HDFC BANK", "HDFC"), ("ICICI BANK", "ICIC"),
    ("AXIS BANK", "UTIB"), ("KOTAK MAHINDRA BANK", "KKBK"), ("PUNJAB NATIONAL BANK", "PUNB"),
    ("BANK OF BARODA", "BARB"), ("CANARA BANK", "CNRB"), ("YES BANK", "YESB"),
    ("IDFC FIRST BANK", "IDFB"), ("UNION BANK OF INDIA", "UBIN"), ("INDUSIND BANK", "INDB"),
    ("FEDERAL BANK", "FDRL"), ("BANK OF INDIA", "BKID"), ("INDIAN BANK", "IDIB"),
    ("AIRTEL PAYMENTS BANK", "AIRP"), ("PAYTM PAYMENTS BANK", "PYTM"),
]

CITIES = ["MUMBAI", "DELHI", "BANGALORE", "BENGALURU", "HYDERABAD", "CHENNAI", "KOLKATA", "PUNE",
          "AHMEDABAD", "JAIPUR", "LUCKNOW", "KOCHI", "INDORE", "BHOPAL", "NAGPUR", "SURAT",
          "CHANDIGARH", "GURGAON", "NOIDA", "THANE", "NAVI MUMBAI", "COIMBATORE", "VIZAG", "PATNA",
          "BHUBANESWAR", "GUWAHATI", "MYSORE", "NASHIK", "VADODARA", "LUDHIANA"]

# UPI handle suffixes seen for people and for merchants.
PERSON_HANDLES = ["okaxis", "okicici", "oksbi", "okhdfcbank", "ybl", "ibl", "axl", "paytm", "ptyes",
                  "ptsbi", "pthdfc", "ptaxis", "upi", "apl", "yapl", "axisbank", "icici", "sbi",
                  "kotak", "hdfcbank", "freecharge", "jupiteraxis", "fam", "slc", "naviaxis",
                  "superyes", "idfcbank", "airtel", "waicici", "waaxis"]
MERCHANT_HANDLES = ["ybl", "axisbank", "icici", "hdfcbank", "yesbank", "paytm", "okbizaxis",
                    "okbizicici", "axb", "ptys", "ikwik", "kotak", "sbi", "fbpe", "apl", "rzp",
                    "cashfree", "pinelabs", "idfcbank", "indus"]

# Payment apps whose name alone sometimes appears as the whole narration.
PAY_APPS = ["GPAY", "PAYTM", "PHONEPE", "BHARATPE", "AMAZONPAY", "MOBIKWIK", "CRED", "BHIM",
            "SUPERMONEY", "NAVI", "PAYTMQR", "PAYZAPP", "POPCLUB"]

MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]

# UPI remark/note pools per category (the free text the payer types, or app default).
GENERIC_NOTES = ["UPI", "Payment from Ph", "Paid via CRED", "Sent from Paytm", "PAY TO", "NA", "",
                 "Pay", "Payment", "UPI Payment", "collect-pay-re", "Paid by PhonePe", "-",
                 "Pay via Razorpay", "UPIIntent", "payment on", "Transfer"]
CATEGORY_NOTES = {
    "FOOD_DINING": ["food", "dinner", "lunch", "breakfast", "snacks", "order", "chai", "party"],
    "GROCERIES": ["grocery", "groceries", "milk", "vegetables", "sabzi", "ration", "fruits", "kirana"],
    "SHOPPING": ["order", "shopping", "clothes", "shoes", "gift", "purchase"],
    "TRANSPORT": ["ride", "trip", "cab", "auto", "metro", "toll", "parking"],
    "FUEL": ["petrol", "diesel", "fuel", "cng"],
    "TRAVEL": ["booking", "ticket", "tickets", "hotel", "trip", "pnr"],
    "BILLS_UTILITIES": ["recharge", "bill", "electricity", "mobile recharge", "broadband", "gas",
                        "maintenance", "dth", "postpaid", "lpg"],
    "RENT": ["rent", "house rent", "RENT", "room rent", "pg rent", "flat rent", "rent + maintenance"],
    "ENTERTAINMENT": ["subscription", "movie", "tickets", "renewal", "membership"],
    "HEALTH": ["medicine", "medicines", "doctor", "consultation", "tests", "pharmacy"],
    "EDUCATION": ["fees", "school fees", "tuition", "course", "coaching fee", "exam fee"],
    "PERSONAL_CARE": ["haircut", "salon", "gym fee", "membership", "service"],
    "EMI_LOAN": ["emi", "loan emi", "EMI"],
    "CREDIT_CARD_BILL": ["cc bill", "card payment", "credit card"],
    "INSURANCE": ["premium", "policy", "renewal"],
    "INVESTMENT": ["sip", "investment", "mf", "lumpsum"],
    "TRANSFER_OUT": ["thanks", "for you", "return", "split", "share", "borrowed", "dinner share",
                     "trip share", "gift", "home", "for mom", "papa", "pocket money"],
    "TRANSFER_IN": ["thanks", "return", "split", "share", "from papa", "gift", "refund of loan",
                    "trip share", "your share"],
}
